# Research Specialist Agent
# Example agent definition file

name: "researcher"
agent_type: "tool_calling"
role: |
  Research specialist. Search, fetch, summarize. Be concise.

tools:
  - tavily_web_search
  - fetch_webpage_markdown

model:
  provider: "openai"
  model: "gpt-4o"
  temperature: 0.7
  max_tokens: 1500

settings:
  verbosity: 5
  max_steps: 6

metadata:
  description: "Research and information gathering specialist for technical topics"
  author: "system"
  version: "1.0.1"
